# Generated by Django 2.0.7 on 2020-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Mobile_NO', models.BigIntegerField()),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
