# Generated by Django 2.0.7 on 2020-03-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Email_ID',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='First_Name',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Last_Name',
            new_name='last_Name',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='Password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='Mobile_NO',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='username',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
