# Generated by Django 2.0.7 on 2020-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200330_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_No', models.BigIntegerField(blank=True)),
                ('Profile_Picture', models.ImageField(blank=True, upload_to='pics')),
                ('DOB', models.DateField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
