# Generated by Django 2.0.7 on 2020-03-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_userprofilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='Contact_No',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
