# Generated by Django 2.0.7 on 2020-03-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20200331_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='Contact_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
