# Generated by Django 2.0.7 on 2020-04-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200331_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
