# Generated by Django 2.0.7 on 2020-03-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_IBMR', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('Mob_No', models.BigIntegerField()),
                ('temp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=15)),
                ('Event_Protocols', models.TextField()),
                ('Event_Poster', models.ImageField(upload_to='pics')),
                ('About_Event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Mobile_NO', models.BigIntegerField()),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
