# Generated by Django 2.0.7 on 2020-03-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
