# Generated by Django 2.0.7 on 2020-03-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_gallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=60)),
                ('Contact_No', models.CharField(max_length=12)),
                ('Post', models.CharField(max_length=30)),
                ('DP', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlidesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pics')),
                ('About_1', models.CharField(max_length=100)),
                ('About_2', models.CharField(max_length=100)),
                ('About_3', models.CharField(max_length=100)),
            ],
        ),
    ]
