# Generated by Django 2.0.7 on 2020-03-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200331_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='DP',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='Email_ID',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='homeslidesmodel',
            name='About_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeslidesmodel',
            name='About_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeslidesmodel',
            name='About_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
