# Generated by Django 2.0.7 on 2020-04-19 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20200331_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_Name', models.CharField(max_length=30)),
                ('Place', models.CharField(max_length=30)),
                ('College_Email_ID', models.EmailField(max_length=30)),
                ('Mob_No', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutModel',
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.DeleteModel(
            name='CoordinatorsModel',
        ),
        migrations.DeleteModel(
            name='EventsModel',
        ),
        migrations.DeleteModel(
            name='GalleryModel',
        ),
        migrations.DeleteModel(
            name='HomeSlidesModel',
        ),
        migrations.DeleteModel(
            name='ProtocolsModel',
        ),
    ]
