# Generated by Django 2.0.7 on 2020-04-19 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registrationmodel_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
